# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build PyDF Annots - GUI for MacOS

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

    # Don't trigger if it's just a documentation update
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '**.yml'
      - '**.sh'
      - '**.bat'
      - 'tests/**'
      - 'doc/**'
      - '.vscode/*'
      - 'Dockerfile'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
      - '.dockerignore'
      - 'spec.json'
      - 'files.txt'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyinstaller
          pip install -r requirements.txt
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g appdmg
      - name: build binary
        run: |
          python setup.py build_binary
      - name: upload build
        uses: actions/upload-artifact@v3
        with:
          name: mac-os-build
          path: dist/*.dmg
      - name: Print files
        run: |
          echo %cd%
          dir dist
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          generate_release_notes: true
